name: lol_lockfile
description: get all data from the lockfile located in the league of legends directory, working on Windows & Mac os for now.
version: 0.0.4
homepage: https://github.com/averageSadGhost/lol_lockfile

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  logger: ^1.3.0

dev_dependencies:

flutter:

platforms:
  windows:
  macos: 